services:
  db:
    image: postgres:14.15-alpine3.21
    restart: always
    container_name: bueboka-postgres
    environment:
      POSTGRES_DB: bueboka
      POSTGRES_USER: bueboka
      POSTGRES_PASSWORD: bueboka
    ports:
      - '5432:5432'
    volumes:
      - bueboka_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bueboka -d bueboka']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  bueboka_pgdata:
