services:
  db:
    image: postgres:14.15-alpine3.21
    restart: always
    container_name: Bueboka
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
