-- AlterTable
ALTER TABLE "bows" ALTER COLUMN "eyeToNock" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "aimMeasure" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "eyeToSight" SET DATA TYPE DOUBLE PRECISION;
